### ISSUE TITLE
dmd failed with exit code 1.

### ISSUE THREAD

**Issue by meaning42** [HaCk3Dq/vk#14]
`vk ~master: building configuration "application"...
u become 313373 now
Linking...
/usr/bin/ld: /usr/lib/libphobos2.a(deflate.o): unrecognized relocation (0x2a) in section ` `.text' `
`/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
--- errorlevel 1
dmd failed with exit code 1.
`

**Comment by substanceof** [comment]
Дистр?

**Comment by meaning42** [comment]
Linux arch 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux

**Comment by substanceof** [comment]
@meaning42 `sudo pacman -Q | grep -E "dmd|dub|phobos"`

**Comment by meaning42** [comment]
@substanceof 
`dmd 2.071.0-1
dub 0.9.24-1
libphobos-devel 2.071.0-1`
