### ISSUE TITLE
Падение от аудиозаписи с длинным названием в маленьком окне

### ISSUE THREAD

**Issue by futuarmo** [HaCk3Dq/vk#21]
Lubuntu 14.04 LTS, 32-bit, dmd 2.071.0
Когда включаю песню 
2 Chainz - Crib In My Closet (Feat. A$AP Rocky & Rick Ross) [prod. by Metro Boomin & 808 Mafia] 
с маленьким окном (название полностью не влезает), программа работает дальше, но интерфейс пропадает, консоль выдает (песня при этом воспроизводится):
core.exception.OutOfMemoryError@src/core/exception.d(693): Memory allocation failed----------------
??:? _d_newarrayU [0x83859c3]in(int, char**, extern (C) int function(char[]??:? _d_newarrayiT [0x8385abf]ate()) [0x838439c]
/usr/include/dmd/phobos/std/array.d:1261 pure nothrow @safe immutable(char)[] std.array.replicate!(immutable(char)[]).replicate(immutable(char)[], uint) [0x831027b]
source/musicplayer.d:161 app.ListElement[] musicplayer.MusicPlayer.getMplayerUI(int) [0x835cce0]tryExec(scope void delegate()) [0x838439c]
source/app.d:1018 app.ListElement[] app.GetMusic() [0x830c557]
source/app.d:431 void app.bodyToBuffer() [0x8307c9b]
source/app.d:1159 _Dmain [0x830d1b0]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x838444a]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x838439c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x8384406]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x838439c]
??:? _d_run_main [0x838432e]
??:? main [0x835a05b]
??:? __libc_start_main [0xb7340a82]

При запуске в большом окне проигрывается нормально.
На других песнях проблемы такой нет
Размеры окон:
![2016-05-14-110638_1366x768_scrot](https://cloud.githubusercontent.com/assets/9935446/15267223/dd066ed0-19cc-11e6-9854-cde875ea931e.png)
![2016-05-14-110645_1366x768_scrot](https://cloud.githubusercontent.com/assets/9935446/15267224/dd0a85b0-19cc-11e6-86dd-06ed796315cf.png)

**Comment by HaCk3Dq** [comment]
Ветка какая или версия?

**Comment by futuarmo** [comment]
Версия 1.2.2, ветка master (версию взял из dub.json)

**Comment by substanceof** [comment]
@futuarmo 1.2.2 это версия библиотеки dcrypto

**Comment by HaCk3Dq** [comment]
забрал баг
