### ISSUE TITLE
Клиент не реагирует после перехода на вкладку музыка

### ISSUE THREAD

**Issue by Isseq** [HaCk3Dq/vk#23]
Клиент не реагирует ни на какие действия после перехода на вкладку музыка.
Аудиозаписей в вк у меня нет.

vk 0.7.1a

**Comment by HaCk3Dq** [comment]
Из мастера собери и еще раз постести

**Comment by substanceof** [comment]
или обновись до 0.7.2

**Comment by substanceof** [comment]
Напиши,  если проблема есть в 072
