### ISSUE TITLE
Access token is not being saved

### ISSUE THREAD

**Issue by Fantaser99** [HaCk3Dq/vk#24]

**Comment by 8084** [comment]
Are you trying to close app by hitting Ctrl+C?

**Comment by Fantaser99** [comment]
Yes, but i tried to close it with Exit button, it gives the same effect.

**Comment by 8084** [comment]
Your version?

**Comment by Fantaser99** [comment]
vk-cli v0.7.2

**Comment by substanceof** [comment]
Точно есть доступ к ~ ?

**Comment by Fantaser99** [comment]
Я ничего не делал, оно просто само начало работать. Закрываю баг за отсутствием проблемы (хз, в чем была проблема)
