### ISSUE TITLE
Не проигрывается музыка (не успевает подключиться к сокету) 

### ISSUE THREAD

**Issue by RustemHaydarov** [HaCk3Dq/vk#26]
Ubuntu 16.04 при попытке воспроизведения музыки пишет "mpv не установлен или работает неверно". У меня стоит версия mpv - 0.17.0, устанавливал через apt. В чем может быть проблема? P.s. при запуске через SUDO такой ошибки не выдает, но музыка просто не проигрывается

**Comment by sirikid** [comment]
А фиг его знает, mpv из репозитория в [релизе][0]? Остальные зависимости проверь тоже.
[0]: https://github.com/HaCk3Dq/vk/releases/tag/0.7.2

**Comment by RustemHaydarov** [comment]
Да вроде все стоит. Все функции работают за исключением музыки. Может это как-то быть связано с тем, что я использую прокси? В логах никаких ошибок не выводит.

**Comment by substanceof** [comment]
Я сделаю сегодня-завтра возможный  фикс, потестишь тогда

**Comment by RustemHaydarov** [comment]
хорошо

**Comment by RustemHaydarov** [comment]
не сделали еще фикс?

**Comment by sirikid** [comment]
@RustemHaydarov пока нет

**Comment by substanceof** [comment]
все, у кого не работало: обновитесь до последнего коммита в master и погоняйте

**Comment by substanceof** [comment]
о результатах сюда

**Comment by mageofdust** [comment]
На арче та же проблема. Пробовал ставить из master - не помогло. Вне зависимости от использования sudo, в первый запуск жалуется на mpv, потом не жалуется и просто не проигрывает

**Comment by substanceof** [comment]
@mageofdust лог с мастера пожалуйста (/tmp/vkcli-log/)

**Comment by alexdless** [comment]
Решилось банальной переустановкой mpv

**Comment by mageofdust** [comment]
@substanceof [vklog_11jun2016-10:55:07-NOVT.txt](https://github.com/HaCk3Dq/vk/files/310104/vklog_11jun2016-10.55.07-NOVT.txt)

**Comment by substanceof** [comment]
@mageofdust у тебя либо mpv стартует дольше 24 секунд,  либо он слишком старый.  Какая версия?

**Comment by substanceof** [comment]
@mageofdust еще сделай `git checkout issue26` и пересобери через `dub build --force`
Накидал дополнительных логов для плеера,  скинь сюда как погоняешь

**Comment by mageofdust** [comment]
@substanceof Arch Linux x64, mpv 0.17, все свежее, обнова сегодня делалась. вот новый лог, в этот раз ждал, но все равно не работает. 
[vklog_11jun2016-20:02:04-NOVT.txt](https://github.com/HaCk3Dq/vk/files/310280/vklog_11jun2016-20.02.04-NOVT.txt)
mpv зависит от ipv6? у меня он отключен по причине неполадок, так что возможно дело в этом

**Comment by substanceof** [comment]
@mageofdust ipv6 не причем.  Сделай пулл на той ветке и кинь новый лог. Еще скопируй прямую ссылку на какое-нибудь аудио из вк и сделай `mpv [link]`. Заработает? Что выведет? Очень вероятно,  что проблема в звуковом выходе

**Comment by mageofdust** [comment]
@substanceof в mpv пробовал ссылки из вк и из soundcloud, результат одинаковый [vklog_11jun2016-23:40:40-NOVT.txt](https://github.com/HaCk3Dq/vk/files/310397/vklog_11jun2016-23.40.40-NOVT.txt)
[mpv_output.txt](https://github.com/HaCk3Dq/vk/files/310398/mpv_output.txt)

**Comment by substanceof** [comment]
@mageofdust Это явно не баг клиента.  А вообще проверь resolv.conf

**Comment by substanceof** [comment]
За сим баг закрываю. Если у кого еще что по mpv - делайте новый тикет
