### ISSUE TITLE
Добавленная на сайте музыка не отображается в клиенте

### ISSUE THREAD

**Issue by ohohohohoho** [HaCk3Dq/vk#27]
Если добавить новую музыку в аккаунт, то она не появится в этой программе до тех пор, пока не перезагрузишь ее. Перезагрузка страницы (клавиша R) не помогает в данной ситуации.

**Comment by substanceof** [comment]
Только что попробовал и во время проигрывания и до: все нормально
Точно нет каких-то дополнительных условий?

**Comment by ohohohohoho** [comment]
Баг удалось воспроизвести вновь. OS: Debian Jessie, vk master

**Comment by substanceof** [comment]
Не воспроизводится
Если найдешь точные обстоятельства бага и последовательность действий, напиши сюда, переоткроем
