### ISSUE TITLE
/tmp/vkdbg

### ISSUE THREAD

**Issue by TyanNN** [HaCk3Dq/vk#28]
Если программа впервые запущена от рута, то папка создаётся от рута, а значит никто больше использовать её не может.  Возможное решение: делать `chmod +rwx` при создании

**Comment by sirikid** [comment]
Решение: не запускать программу от рута

**Comment by substanceof** [comment]
@TyanNN  Сейчас в мастере используется другая система логов и сокетов, так что уже не актуально
