### ISSUE TITLE
SEGFAULT при регистрации

### ISSUE THREAD

**Issue by petRUShka** [HaCk3Dq/vk#32]
Начинаю регистрацию:
> You need to copy access token from your web browser. Would you like to launch it now? [Y/n]Y
> Please allow access to your data and then copy link from the address bar.
> Insert your link `here: https://oauth.vk.com/blank.html#access_token=<TOKEN>&expires_in=0&user_id=<USER_ID>`

После нажатия ENTER вылетает в segfault:
 
> Program received signal SIGSEGV, Segmentation fault.

Данные из gdb (production mode):
`0x000000000075c26c in _aaGetY ()`

**Comment by petRUShka** [comment]
Если в ~/.vkrc прописать token и user_id, то всё ок

**Comment by substanceof** [comment]
Уже слышал об этом баге,  посмотрю сегодня

**Comment by Shoomaher** [comment]
Также столкнулся с ошибкой сегментирования. Прописал свой токен и user_id: программа показывает интерфейс, но пишет, что "нет соединения".

**Comment by substanceof** [comment]
@Shoomaher Нужен лог

**Comment by substanceof** [comment]
Проблема вызвана флагом оптимизации для dmd, так что в пакете aur я пока его уберу

**Comment by Shoomaher** [comment]
@substanceof Уже разобрался. Не правильно прописал конфиг. В общем, всё как у petRUShka.
