### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by VerusGott** [HaCk3Dq/vk#35]
После первого запуска и запроса токена - выдавало ApiErrorException: User authorization failed: invalid access_token (4). Заглянул в .vkrc, там до _моего_ токена не хватало ровно 8 знаков в конце (как это вообще вышло?). Отредактировал токен, но ситуация особо не изменилась. В приложении "No connection" и отсутствие реакции на попытки обновить/перезайти. 
Лог - http://pastebin.com/qjTSqUH1

(Конкретно, тут два баг репорта - по какой-то причине токен в конфиг прописывается не целиком; no connection даже с правильным токеном)
Система - Arch Linux, пакет из AUR.

**Comment by substanceof** [comment]
Про токен трудно что-то сказать, возможно, обрезало при вставке. Ссылку вставлял или только сам токен? Какой терминал?

**Comment by substanceof** [comment]
на счет коннекшена: попробуй удалить .vkrc в домашней директории и еще раз авторизироваться. В логах нету строк request: ..., как будто что-то случилось с curl

**Comment by VerusGott** [comment]
Вставлял ссылку, терминал - urxvt-unicode. Ради интереса только что поставил gnome-terminal, удалил .vkrc и вставил нужную ссылку - токен опять обрезало.

На счет коннекшна - .vkrc уже удалял и не раз. Не помогает. Собрал ради интереса последнюю версию curl с GitHub, тоже ничего не изменилось.
(начинает казаться, что это арчепроблемы как они есть, но куда тогда копать?)

**Comment by substanceof** [comment]
Я правильно понимаю, что после вставки токен в клнфиге был 77 символов в длинну?

**Comment by VerusGott** [comment]
Мм.
rm ~/.vkrc
vk
вставляю полученную ссылку (`https://oauth.vk.com/blank.html#access_token=8a2dc***bd4119c9fb*****56fe253350a6149b80921e7bdac367744b440***3303*c*fdc*f448aeb13669dc76e75&expires_in=0&user_id=373488326`)
получаю no connection
в .vkrc токен имеет вид `8a2dc***bd4119c9fb*****56fe253350a6149b80921e7bdac367744b440***3303*c*fdc*f448aeb1366`
вставляю полную версию: `8a2dc***bd4119c9fb*****56fe253350a6149b80921e7bdac367744b440***3303*c*fdc*f448aeb13669dc76e75`

До правки - 85, после - 93

**Comment by HaCk3Dq** [comment]
Скорее всего vk увеличили длину токена, раньше был 85
Из-за этого и вся херня

**Comment by VerusGott** [comment]
Я тоже об этом подумал сразу. Фикс в 0.7x будет, или теперь ждать 0.8 ветку? :^

**Comment by HaCk3Dq** [comment]
У тебя каждый раз генерит токен по 93 символа?

**Comment by VerusGott** [comment]
Да.

**Comment by HaCk3Dq** [comment]
В новостях vk api ни слова про новый токен, что довольно странно

Есть варик еще у кого-нибудь попросить авторизоваться, кто еще не юзал vk-cli?

**Comment by VerusGott** [comment]
Попробовал с другого аккаунта, что зарегистрован ещё в 2009 (мало ли, вдруг новая генерация токена для новых юзеров), там тоже 93 знака.

**Comment by substanceof** [comment]
Тоже попробовал на одном из старых акков, где никогда не получал токен, но там 85 символов

**Comment by VerusGott** [comment]
Попробовал с _третьего_ аккаунта. Токен определенно имеет длину в 93 символа.

**Comment by substanceof** [comment]
вк что-то однознано мутит, и в общем мы бы уже пофиксили, но есть проблема, которую надо бы решать с дебаггером, следовательно, где-то достать свой 93 символьный токен

**Comment by VerusGott** [comment]
Могу без смс и регистрации отдать один из своих аккаунтов для дебага.

**Comment by substanceof** [comment]
во, спасибо.
Скинь тогда токен мне в личку http://vk.com/id282386942

**Comment by substanceof** [comment]
https://github.com/HaCk3Dq/vk/commit/f9983ceb9f9486218cc155995e689c3eb83ce645

**Comment by F0RIS** [comment]
Пытаюсь запустить vk-cli на впске (пробовал на двух). В обоих случаях получаю no connection
![image](https://cloud.githubusercontent.com/assets/10178982/17651539/f3b5400a-6271-11e6-83f8-9c04405daf75.png)
При этом токен у меня длинной в 85 символов..
![image](https://cloud.githubusercontent.com/assets/10178982/17651559/5fc0f596-6272-11e6-942a-26b4864e89ee.png)
Ставил и релизный деб пакет и собирал прям там же на впс репы. Результат тот же :(


(dmd-2016-08-14)root@node-512mb-lon1-01:~/vk# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
(dmd-2016-08-14)root@node-512mb-lon1-01:~/vk# uname -a
Linux node-512mb-lon1-01 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
(dmd-2016-08-14)root@node-512mb-lon1-01:~/vk#

**Comment by substanceof** [comment]
@F0RIS Лог бы.  (`/tmp/vkcli-log/`)

**Comment by F0RIS** [comment]
@substanceof я бы сразу логи привел, но не знал где они лежат)

vklog-latest

vk-cli 0.7.4 log
2016-Aug-18 16:11:30.4807619
GC signals: 34 35
rid: -1906717613
rid: 1304879284
rid: -697129341
thread started for: runplayer
mpv - starting
thread started for: async_single s_self_resolve
asyncLongpoll called
request: https://api.vk.com/method/execute.accountInit?v=5.50&access_token=***
thread started for: longpoll
longpoll is waiting for api init...
mpv - running
mpv - waiting for socket spawn...
ApiErrorException: Validation required: please open redirect_uri in browser 509222078
mpv - waiting for socket spawn...
mpv - waiting for socket spawn...
mpv - waiting for socket spawn...
mpv - waiting for socket spawn...
mpv - waiting for socket spawn...
mpv - waiting for socket spawn...
mpv - cmd: exit
mpv - req: noinit

**Comment by substanceof** [comment]
@F0RIS защита от "выхода из необычного места". Попробуй залогинится в браузере с впски (через впн как вариант),  токен должен заработать без перегенерации

**Comment by F0RIS** [comment]
@substanceof у меня там нет ДЕ, как я это сделаю))) разве что текстовым бразуером пробовать?

**Comment by substanceof** [comment]
@F0RIS ну через апи это никак не сделать, к сожалению. Можно попробовать через lynx, но я не думаю, что получится. Проще все таки впн. Или через тор выйти с exit ноды из того же государства (где впска) и пройти валидацию для него.
