### ISSUE TITLE
using application through proxy

### ISSUE THREAD

**Issue by zablotski** [HaCk3Dq/vk#39]
Hello 

How I can use application through proxy?

**Comment by substanceof** [comment]
vkcli currently isn't supports proxy, but we can make workaround for you.You build vk from source or you're using Deb?

**Comment by zablotski** [comment]
I've used deb package. 

Probably most common workaround will be to use `http_proxy` environment variable or `vk-cli` settings option like `Main color` or `Language`

Thank you :)

**Comment by HaCk3Dq** [comment]
Okay, will probably make it in 0.8 release
