### ISSUE TITLE
Музыка не работает.

### ISSUE THREAD

**Issue by fadeev10clouds** [HaCk3Dq/vk#4]
Скомпилил на убунте, музыка не играется, mplayer стоит.

**Comment by Architektor** [comment]
В логах которые в /tmp/vkdbg ничего, только новые сообщения. Когда выбираю музычку, просто ничего не происходит, показывает / 1:08 например в длительности.

**Comment by substanceof** [comment]
Сделай `git checkout issue4`
Кинул доп. логов для плеера

**Comment by diman3241** [comment]
Зашел в клиент, потыкал песенки из списка, не работают.

>
    log
    rid: -1919675574
    rid: 1427206876
    rid: 1308380919
    offline status sent (shed)
    sheduled onlineNotifier shutdown
    output try
    request: https://api.vk.com/method/execute.accountInit?v=5.50&access_token=***
    request: https://api.vk.com/method/account.setOffline?voip=0&v=5.50&access_token=***
    longpoll is waiting for api init...
    output try
    last mp: Failed to open /etc/mplayer/input.conf.
    longpoll is starting...
    request: https://api.vk.com/method/messages.getLongPollServer?need_pts=1&use_ssl=1&v=5.50&access_token=***
    output try
    longpoll server: 
    {
        "key": "023cd354f6c25f721b6939df487fa8b7b79f7ecd",
        "pts": 1726592,
        "server": "imv4.vk.com\/im1004",
        "ts": 1633897639
    }
    longpoll works
    output try
    request: https://api.vk.com/method/audio.get?count=100&v=5.50&access_token=***
    output try
    request: https://api.vk.com/method/audio.get?offset=100&count=100&v=5.50&access_token=***
    output try
    output try
    output try
    output try
    last mp: 
    catched trackOver
    output try
    last mp: 
    output try
    output try
    output try
    last mp: 
    output try
    output try
    output try
    output try
    output try
    output try
    output try
    output try
    last mp: 
    output try
    output try
    output try
    output try
    last mp: 
    output try
    output try
    output try
    output try
    output try
    output try
    last mp: 
    output try
    last mp: 
    output try
    last mp: 
    output try
    last mp: 
    output try
    last mp:

**Comment by substanceof** [comment]
Проблема крылась в mplayer:
старые версии не могут в https. 
Пофикшено, будет в следующем патчсете

**Comment by substanceof** [comment]
@diman3241 попробуй погонять на мастере, работает музыка или нет, но судя по `last mp: Failed to open /etc/mplayer/input.conf.` у тебя проблемы с мплеером.
