### ISSUE TITLE
Вылетает при наборе сообщения

### ISSUE THREAD

**Issue by pvarenik** [HaCk3Dq/vk#41]
Вылетает при наборе сообщения
Шаги:
1. Заходим в сообщения и начинаем набирать сообщение
2. Набираем две звездочки (*)
3. Жмем влево (чтобы начать набирать между звездочками)
4. Набираем любой символ

**Comment by bcskda** [comment]
С латиницей все нормально, падает с кириллицей (прошу прощения, что вмешался)

**Comment by HaCk3Dq** [comment]
Да, я знаю об этом баге, но хз как пофиксить)
Там код пиздец
