### ISSUE TITLE
Обрезан Unicode-символ

### ISSUE THREAD

**Issue by bcskda** [HaCk3Dq/vk#42]
При обновлении частично обрезана круговая стрелка. Не зависит от размеров окна и полноэкранного режима.
```
gnome-terminal 3.6.2
```
![2016-09-18 13 06 34](https://cloud.githubusercontent.com/assets/19408762/18614904/22111f30-7da9-11e6-9790-ee2f5f8053af.png)

**Comment by substanceof** [comment]
Эксклюзивный (и, в общем, давно известный) косяк гномотерминала. Как фиксить - идей пока нет
