### ISSUE TITLE
VK-CLI HJKL-bug

### ISSUE THREAD

**Issue by m65v19** [HaCk3Dq/vk#44]
![screenshot_2016-10-12_08-32-02](https://cloud.githubusercontent.com/assets/15930110/19296650/0758e740-905f-11e6-8568-745d7aaa5df6.png)

[vklog-latest.zip](https://github.com/HaCk3Dq/vk/files/523501/vklog-latest.zip)

1]Включаем любой трек
2]Переходим в "Help"
3]Беспорядочно нажимаем на JKL
ИТОГ: Получаем баг, прога зависает намертво, однако музыка продолжает играть. Не помогает "q", только Ctrl+C.

**Comment by sirikid** [comment]
1. Баг воспроизводится только если включена музыка?
2. Баг воспроизводится только в разделе Help?

**Comment by m65v19** [comment]
FIX
Баг воспроизводится:
1)Необходимо выйти вверх или вниз за пределы списка.
2)Нажать "Вправо", "L", "D"  т.е. попытаться "войти" в подменю несуществующего эл-та.
ИТОГ:Получаем баг, прога зависает намертво, однако музыка продолжает играть. Не помогает "q", только Ctrl+C.
Баг воспроизводится в следующих ситуациях:
0) Не важно, включена музыка или нет.
1) Баг появляется только там, где отсутсвует цикличная прокрутка, т.е. существует возможность выйти  за пределы списка, т.е. вверх или вниз, а это пункты:
Help; Music; Settings. 
2) Для бага не имеет значения, какими сочетаниями клавиш мы передвигаеся по списку.

**Comment by substanceof** [comment]
В музыке в конце списка сколько пустых строк?

**Comment by m65v19** [comment]
Если под кол-вом пустых строк подразумевалось кол-во строк таких, что не видны, однако через какое-то их кол-во происходит возврат на 1ю строку(видимую), то таких строк насчитал 6.
![screenshot_2016-10-12_23-40-38](https://cloud.githubusercontent.com/assets/15930110/19323189/b0e7343c-90dd-11e6-902d-debe2b805b7c.png)

**Comment by substanceof** [comment]
Все понятно, спасибо

**Comment by substanceof** [comment]
Хотя честно говоря, я не уверен, что в ветке 0.7 этот баг вообще окажется пофикшен, но мв верим:
