### ISSUE TITLE
[RFC] Просмотр вложений

### ISSUE THREAD

**Issue by Hummer12007** [HaCk3Dq/vk#45]
Стоило бы добавить подобное: https://sr.ht/9uUP.patch

**Comment by HaCk3Dq** [comment]
Зачем в ишью кинул?
форк - отдельная ветка - пулл реквест

**Comment by Hummer12007** [comment]
Это скорее вопрос.

**Comment by Hummer12007** [comment]
А

**Comment by substanceof** [comment]
@Hummer12007 Не надо, я уже доделал хд

**Comment by substanceof** [comment]
@Hummer12007 взгляни на ветку (https://github.com/HaCk3Dq/vk/tree/0.7-attachments-patch)
Если нечего добавить, то я мержу

**Comment by Hummer12007** [comment]
Есть что, минут через 5 пр открою.

**Comment by substanceof** [comment]
открывай тогда от той ветки

**Comment by Hummer12007** [comment]
Не все так просто...
https://github.com/HaCk3Dq/vk/pull/46

**Comment by substanceof** [comment]
Взгляни еще раз на ту ветку
Мержить?

**Comment by Hummer12007** [comment]
Убрать комментарий в 641, и можно

**Comment by substanceof** [comment]
Мержнул. Спасибо
