### ISSUE TITLE
Cannot build from sources

### ISSUE THREAD

**Issue by tazhate** [HaCk3Dq/vk#5]
On alpha and master. 

`vk ~master: building configuration "__test__library__"...
/home/taz/vk/source/vkapi.d:750:1: ошибка: std.regex.Thread(DataIndex) at /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/include/d/std/regex.d:4588:1 conflicts with core.thread.Thread at /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/include/d/core/thread.di:549:1
 class AsyncOrder : Thread {
 ^
/home/taz/vk/source/vkapi.d:750:1: ошибка: module vkapi struct std.regex.Thread(DataIndex) is private
 class AsyncOrder : Thread {
 ^
/home/taz/vk/source/vkapi.d:750:1: ошибка: struct std.regex.Thread(DataIndex) is used as a type
 class AsyncOrder : Thread {
 ^
/home/taz/vk/source/vkapi.d:811:1: ошибка: std.regex.Thread(DataIndex) at /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/include/d/std/regex.d:4588:1 conflicts with core.thread.Thread at /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/include/d/core/thread.di:549:1
 class AsyncSingle : Thread {
 ^
/home/taz/vk/source/vkapi.d:811:1: ошибка: module vkapi struct std.regex.Thread(DataIndex) is private
 class AsyncSingle : Thread {
 ^
/home/taz/vk/source/vkapi.d:811:1: ошибка: struct std.regex.Thread(DataIndex) is used as a type
 class AsyncSingle : Thread {
 ^
/home/taz/vk/source/vkapi.d:915:1: ошибка: std.regex.Thread(DataIndex) at /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/include/d/std/regex.d:4588:1 conflicts with core.thread.Thread at /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/include/d/core/thread.di:549:1
 class Longpoll : Thread {
 ^
/home/taz/vk/source/vkapi.d:915:1: ошибка: module vkapi struct std.regex.Thread(DataIndex) is private
 class Longpoll : Thread {
 ^
/home/taz/vk/source/vkapi.d:915:1: ошибка: struct std.regex.Thread(DataIndex) is used as a type
 class Longpoll : Thread {
 ^
/home/taz/vk/source/vkapi.d:1205:1: ошибка: std.regex.Thread(DataIndex) at /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/include/d/std/regex.d:4588:1 conflicts with core.thread.Thread at /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/include/d/core/thread.di:549:1
 class OnlineNotifier : Thread {
 ^
/home/taz/vk/source/vkapi.d:1205:1: ошибка: module vkapi struct std.regex.Thread(DataIndex) is private
 class OnlineNotifier : Thread {
 ^
/home/taz/vk/source/vkapi.d:1205:1: ошибка: struct std.regex.Thread(DataIndex) is used as a type
 class OnlineNotifier : Thread {
 ^
/usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/include/d/gcc/backtrace.di:393:16: ошибка: module unwind is in file 'gcc/unwind.d' which cannot be read
         import gcc.unwind;
                ^
import path[0] = /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.5/include/d
import path[1] = /home/taz/vk/source
import path[2] = /home/taz/.dub/packages/dcrypto-1.2.2/source
import path[3] = /home/taz/.dub/packages/openssl-1.1.4_1.0.1g
import path[4] = /home/taz/.dub/packages/ncurses-master
gdc failed with exit code 1.
`

**Comment by substanceof** [comment]
gdc не поддерживается
Ставь dmd

**Comment by edwvee** [comment]
Can't build to:
Fetching dcrypto 1.2.2 (getting selected version)...
Placing dcrypto 1.2.2 to /home/acc/.dub/packages/...
Fetching ncurses ~master (getting selected version)...
Placing ncurses ~master to /home/acc/.dub/packages/...
WARNING: A deprecated branch based version specification is used for the dependency ncurses. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Performing "debug" build using dmd for x86.
dcrypto 1.2.2: building configuration "library"...
ncurses ~master: building configuration "library"...
../../../.dub/packages/ncurses-master/deimos/ncurses/form.d(38,8): Deprecation: module std.c.stdarg is deprecated - Import core.stdc.stdarg instead
vk ~master: building configuration "application"...
source/app.d(345,36): Error: template std.string.center cannot deduce function from argument types !()(string, ulong, char), candidates are:
/usr/include/dmd/phobos/std/string.d(3988,3):        std.string.center(S)(S s, size_t width, dchar fillChar = ' ') if (isSomeString!S)
source/app.d(346,14): Error: template std.string.center cannot deduce function from argument types !()(string, ulong, char), candidates are:
/usr/include/dmd/phobos/std/string.d(3988,3):        std.string.center(S)(S s, size_t width, dchar fillChar = ' ') if (isSomeString!S)
source/app.d(372,44): Error: cannot implicitly convert expression (i) of type ulong to uint
source/app.d(396,44): Error: template std.array.replicate cannot deduce function from argument types !()(string, ulong), candidates are:
/usr/include/dmd/phobos/std/array.d(1252,25):        std.array.replicate(S)(S s, size_t n) if (isDynamicArray!S)
/usr/include/dmd/phobos/std/array.d(1276,17):        std.array.replicate(S)(S s, size_t n) if (isInputRange!S && !isDynamicArray!S)
source/app.d(424,54): Error: cannot implicitly convert expression (i) of type ulong to uint
source/app.d(435,56): Error: cannot implicitly convert expression (i) of type ulong to uint
source/app.d(445,19): Error: cannot implicitly convert expression (cast(ulong)__dollar - utfLength(e.text)) of type ulong to uint
source/app.d(451,17): Error: cannot implicitly convert expression (cast(ulong)__dollar - utfLength(e.text)) of type ulong to uint
source/app.d(507,22): Error: template std.array.replicate cannot deduce function from argument types !()(string, ulong), candidates are:
/usr/include/dmd/phobos/std/array.d(1252,25):        std.array.replicate(S)(S s, size_t n) if (isDynamicArray!S)
/usr/include/dmd/phobos/std/array.d(1276,17):        std.array.replicate(S)(S s, size_t n) if (isInputRange!S && !isDynamicArray!S)
source/app.d(895,41): Error: cannot implicitly convert expression (cast(ulong)(COLS - win.menuOffset) - utfLength(newMsg) - utfLength(e.name) - 8LU - cast(ulong)to(e.unreadCount).length) of type ulong to uint
source/app.d(901,51): Error: template std.array.replicate cannot deduce function from argument types !()(string, ulong), candidates are:
/usr/include/dmd/phobos/std/array.d(1252,25):        std.array.replicate(S)(S s, size_t n) if (isDynamicArray!S)
/usr/include/dmd/phobos/std/array.d(1276,17):        std.array.replicate(S)(S s, size_t n) if (isInputRange!S && !isDynamicArray!S)
source/musicplayer.d(148,42): Error: template std.array.replicate cannot deduce function from argument types !()(string, ulong), candidates are:
/usr/include/dmd/phobos/std/array.d(1252,25):        std.array.replicate(S)(S s, size_t n) if (isDynamicArray!S)
/usr/include/dmd/phobos/std/array.d(1276,17):        std.array.replicate(S)(S s, size_t n) if (isInputRange!S && !isDynamicArray!S)
source/musicplayer.d(149,42): Error: template std.array.replicate cannot deduce function from argument types !()(string, ulong), candidates are:
/usr/include/dmd/phobos/std/array.d(1252,25):        std.array.replicate(S)(S s, size_t n) if (isDynamicArray!S)
/usr/include/dmd/phobos/std/array.d(1276,17):        std.array.replicate(S)(S s, size_t n) if (isInputRange!S && !isDynamicArray!S)
u become 313373 now
dmd failed with exit code 1.

**Comment by tazhate** [comment]
@substanceof какую версию dmd использовать? на 2.066.1 не взлетело.

'vk ~master: building configuration "__test__library__"...
/home/taz/vk/source/vkapi.d(237,26): Deprecation: variable vkapi.VkApi.vkurl const field with initializer should be static, __gshared, or an enum
/home/taz/vk/source/vkapi.d(238,18): Deprecation: variable vkapi.VkApi.vkver const field with initializer should be static, __gshared, or an enum
/home/taz/vk/source/vkapi.d(750,1): Error: std.regex.Thread(DataIndex) at /opt/dmd-2.066/import/std/regex.d(4588,1) conflicts with core.thread.Thread at /opt/dmd-2.066/import/core/thread.d(514,1)
/home/taz/vk/source/vkapi.d(750,1): Error: module vkapi struct std.regex.Thread(DataIndex) is private
/home/taz/vk/source/vkapi.d(750,1): Error: struct std.regex.Thread(DataIndex) is used as a type
/home/taz/vk/source/vkapi.d(751,15): Deprecation: variable vkapi.AsyncOrder.maxFails const field with initializer should be static, __gshared, or an enum
/home/taz/vk/source/vkapi.d(811,1): Error: std.regex.Thread(DataIndex) at /opt/dmd-2.066/import/std/regex.d(4588,1) conflicts with core.thread.Thread at /opt/dmd-2.066/import/core/thread.d(514,1)
/home/taz/vk/source/vkapi.d(811,1): Error: module vkapi struct std.regex.Thread(DataIndex) is private
/home/taz/vk/source/vkapi.d(811,1): Error: struct std.regex.Thread(DataIndex) is used as a type
/home/taz/vk/source/vkapi.d(881,9): Deprecation: variable vkapi.AsyncMan.S_SELF_RESOLVE const field with initializer should be static, __gshared, or an enum
/home/taz/vk/source/vkapi.d(882,9): Deprecation: variable vkapi.AsyncMan.S_ONLINE_STATUS const field with initializer should be static, __gshared, or an enum
/home/taz/vk/source/vkapi.d(883,9): Deprecation: variable vkapi.AsyncMan.S_TYPING const field with initializer should be static, __gshared, or an enum
/home/taz/vk/source/vkapi.d(884,9): Deprecation: variable vkapi.AsyncMan.O_LOADBLOCK const field with initializer should be static, __gshared, or an enum
/home/taz/vk/source/vkapi.d(885,9): Deprecation: variable vkapi.AsyncMan.O_SENDMSG const field with initializer should be static, __gshared, or an enum
/home/taz/vk/source/vkapi.d(915,1): Error: std.regex.Thread(DataIndex) at /opt/dmd-2.066/import/std/regex.d(4588,1) conflicts with core.thread.Thread at /opt/dmd-2.066/import/core/thread.d(514,1)
/home/taz/vk/source/vkapi.d(915,1): Error: module vkapi struct std.regex.Thread(DataIndex) is private
/home/taz/vk/source/vkapi.d(915,1): Error: struct std.regex.Thread(DataIndex) is used as a type
/home/taz/vk/source/vkapi.d(970,16): Deprecation: variable vkapi.Longpoll.longpollRethrow const field with initializer should be static, __gshared, or an enum
/home/taz/vk/source/vkapi.d(1205,1): Error: std.regex.Thread(DataIndex) at /opt/dmd-2.066/import/std/regex.d(4588,1) conflicts with core.thread.Thread at /opt/dmd-2.066/import/core/thread.d(514,1)
/home/taz/vk/source/vkapi.d(1205,1): Error: module vkapi struct std.regex.Thread(DataIndex) is private
/home/taz/vk/source/vkapi.d(1205,1): Error: struct std.regex.Thread(DataIndex) is used as a type
/home/taz/vk/source/vkapi.d(1211,19): Deprecation: variable vkapi.OnlineNotifier.retryMin const field with initializer should be static, __gshared, or an enum
/home/taz/vk/source/vkapi.d(2083,15): Deprecation: variable vkapi.ClMessage.wwmultiplier const field with initializer should be static, __gshared, or an enum
/home/taz/vk/source/musicplayer.d(53,9): Deprecation: variable musicplayer.MusicPlayer.listenWait const field with initializer should be static, __gshared, or an enum
dmd failed with exit code 1.
'

**Comment by edwvee** [comment]
У меня DMD32 D Compiler v2.071.0. Ну логично ж с последними компиляторами проверять.

**Comment by tazhate** [comment]
@edwvee я предпочитаю не ставить замаскированные пакеты :)

**Comment by substanceof** [comment]
@edwvee 32битные системы не поддерживаются пока,  скоро будет воркераунд

**Comment by substanceof** [comment]
@tazhate Нужен последний дмд.  Если никак,  то в релизах лежит бинарник
