### ISSUE TITLE
allow auth without display - just return link

### ISSUE THREAD

**Issue by vitaly-zdanevich** [HaCk3Dq/vk#53]
```
You need to copy access token from your web browser. Would you like to launch it now? [Y/n] 

Please allow access to your data and then copy link from the address bar.
Insert your link here: /bin/sh: 1: xdg-open: not found
```

**Comment by sirikid** [comment]
Пожалуйста,  выложите вывод `which xdg-open`

**Comment by vitaly-zdanevich** [comment]
/usr/bin/xdg-open30.10.2016, 12:15, "Ivan Sokolov" <notifications@github.com>:Пожалуйста,  выложите вывод which xdg-open

**Comment by HaCk3Dq** [comment]
просто поставь xdg-open

**Comment by vitaly-zdanevich** [comment]
тогда открывается браузер lynx или w3m - там не получилось войти Вконтакт - а можно чтобы программа отдала линк для получения токена в локальном графическом браузере? это я пробовал по ssh на удаленной машине, на локальной 32 разрядная система и вообще не запускается программа.

**Comment by HaCk3Dq** [comment]
при авторизации в vk-cli жмешь n и он пишет линк
