### ISSUE TITLE
Юникод и сообщения

### ISSUE THREAD

**Issue by Hummer12007** [HaCk3Dq/vk#57]
💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛💛
может закрашить клиент (при достаточно узком терминале)

**Comment by substanceof** [comment]
Можно наибольшую ширину терминала и точное сообщение, при которых проявляется баг?
И стекстрейс после краша

**Comment by Hummer12007** [comment]
Сообщение в точности те самые сердечки, только в этот раз еще больше: https://sr.ht/5xNk.jpg

**Comment by substanceof** [comment]
Попробуй собрать master и потестить (в ауре есть vk-cli-git)

**Comment by Hummer12007** [comment]
Спасибо! Краши пропали, но текст теперь может разорваться посреди символа юникода.

**Comment by substanceof** [comment]
Это цена отсутствия крашей) 
разрыв - это replacement symbol. Почему парсер юникода из фобоса там спотыкается - мне неизвестно
