### ISSUE TITLE
Помогло исправить ошибку с зависимостью dcrypto.

### ISSUE THREAD

**Issue by diman3241** [HaCk3Dq/vk#6]
diff --git a/dub.json b/dub.json
	index a6ba5f4..3d18b93 100644
	--- a/dub.json
	+++ b/dub.json
	@@ -5,7 +5,7 @@
	"homepage": "https://github.com/HaCk3Dq/vk",
	"dependencies": {
		"ncurses": "~master",
	-    "dcrypto": "~>1.2.2"
	+    "dcrypto": ">0.0.0"
	},
	"buildRequirements": ["allowWarnings"]
	}

**Comment by substanceof** [comment]
Какая ошибка была до замены версии?
