### ISSUE TITLE
Ошибка на вкладке музыки

### ISSUE THREAD

**Issue by Feanor1397** [HaCk3Dq/vk#66]
Словил это, когда открыл вкладку музыки. Сам клиент после этого продолжает работать, но интерфейс не отрисовывается. Повторить не получается, но если что, отпишусь.

core.exception.RangeError@source/app.d(897): Range violation
----------------
??:? _d_arraybounds [0x7a7297]
??:? app.__array [0x773077]
??:? void app.selectEvent() [0x70c479]
??:? void app.nonChatEvents() [0x70be59]
??:? void app.controller() [0x
70b422] ??:? _Dmain [0x710132]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllM
FZ9__lambda1MFZv [0x7aba7a] ??:? void rt.dmain2._d_run_main(int, char**, extern (
C) int function(char[][])*).tryExec(scope void delegate()) [0x7ab9c4] ??:? void r
t.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x7aba36] ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x7ab9c4]
??:? _d_run_main [0x7ab935]
??:? main [0x7730ef]
??:? __libc_start_main [0x60eb3290]

**Comment by Feanor1397** [comment]
Кажется понял. Если открыта вкладка музыки и текущий трек находится ниже того, что отрисовывается на экране, то при нажатии любой клавиши ловим ошибку. Правда если просто прокрутить список, то все нормально будет. Ошибка только тогда, когда играет трек, который находится где-то гораздо ниже списка на экране.

**Comment by HaCk3Dq** [comment]
знаю, в 0.8 будет пофикшено
там полностью переделаю ui
