### ISSUE TITLE
Сломалась аутентификация по токену

### ISSUE THREAD

**Issue by pvarenik** [HaCk3Dq/vk#67]
Ветка master
После сборки спрашивает телефон и пароль, а потом вылетает с ошибкой:
`Error while auth: {"error":"need_validation","validation_type":"2fa_sms","validation_sid":"[SID]","phone_mask":"[MASK]","error_description":"open redirect_uri in browser [5]. Also you can use 2fa_supported param","redirect_uri":"https:\/\/m.vk.com\/login?act=authcheck&api_hash=[HASH]"}
`
_Все что в верхнем регистре и квадратных скобках - это я свою инфу скрыл_
При переходе по redirect_uri запрашивает код, который пришел мне личным сообщением от аккаунта "Администрация". После ввода кода я получаю токен, только вставлять его некуда.

**Comment by SerjAntiquity** [comment]
попробуй токен в .vkrc
`lang = 0
send_online = false
second_color = 2
rainbow = true
main_color = 4
seek_percent_or_value = true
unicode_chars = true
rainbow_in_chat = true
message_setting = 0
show_typing = false
longpoll_wait = 25
show_conv_notif = true
token = paste_your_token_here
auth_v2 = true
`

**Comment by pvarenik** [comment]
та же ошибка
(я так понимаю это тот файл который в домашней директории лежит?)

**Comment by substanceof** [comment]
Сделаю сегодня поддержку двухфакторной

**Comment by pvarenik** [comment]
что-то все не пашет

**Comment by HaCk3Dq** [comment]
Да субстанция забил просто, kek :D

**Comment by pvarenik** [comment]
блин, это я стормозил, читал другой баг и понял что у меня пропущено **auth_v2 = true**, с этим флагом - работает. Но его бы автоматом добавлять
