### ISSUE TITLE
Имею проблему с установкой

### ISSUE THREAD

**Issue by keipa** [HaCk3Dq/vk#7]
dub установлен
Помогите плис
![image](https://cloud.githubusercontent.com/assets/11652476/14821548/d2831ac8-0bd3-11e6-8553-154f588c3ccf.png)

**Comment by sirikid** [comment]
Похоже не установлены указанные библиотеки (openssl, crypto?, ncurses)

**Comment by substanceof** [comment]
Дистрибутив?

**Comment by sirikid** [comment]
@substanceof вангую bash on windows

**Comment by keipa** [comment]
да, стоит баш

**Comment by keipa** [comment]
попробую библиотеки поставить

**Comment by HaCk3Dq** [comment]
ого, если заведется под виндой, то я ахуею ;D

**Comment by sirikid** [comment]
@keipa какая ОС? В README ~~русским по русскому~~ английским по английскому что поддерживается только x86-64 Linux

**Comment by keipa** [comment]
да блаждад, винда стоит

**Comment by keipa** [comment]
ща буду пробовать заводить

**Comment by substanceof** [comment]
удачи хд
отпиши в группу о результатах https://vk.com/hack3d_home
