### ISSUE TITLE
Не хочет логиниться

### ISSUE THREAD

**Issue by CPAllianceP** [HaCk3Dq/vk#70]
Ветка master.
![image](https://cloud.githubusercontent.com/assets/19843908/21698354/42cd2722-d39f-11e6-9f11-40593fecfefc.png)
Всё в картинке. Открыв ссылку в браузере, получаю токен, в .vkrc в ставил - но толку никакого.

**Comment by substanceof** [comment]
В конфиге рядом с токеном обязательно  должен быть пункт `auth_v2 = true`

**Comment by CPAllianceP** [comment]
У меня конфиг вот в таком виде. Что поменять?
![image](https://cloud.githubusercontent.com/assets/19843908/21699697/9e299fa0-d3a5-11e6-94f2-eb8f984bb235.png)

**Comment by substanceof** [comment]
`token = c365...`

**Comment by CPAllianceP** [comment]
теперь просто закрывается без выхлопа

**Comment by CPAllianceP** [comment]
Поставил версию из аура обычную, не -git, теперь опять такой же выхлоп как и с самого начала

**Comment by CPAllianceP** [comment]
можно просто скинуть конфиг со скрытыми ключевыми данными дабы я вставил туда свои? Наверное, простейший вариант, ибо пробелма точно не в самом клиенте

**Comment by substanceof** [comment]
Ну вот только что скопировал свой хд
```
lang = 0
send_online = false
second_color = 1
rainbow = false
main_color = 3
seek_percent_or_value = false
unicode_chars = true
rainbow_in_chat = false
message_setting = 0
show_typing = false
longpoll_wait = 25
show_conv_notif = false
token = ba8...34
auth_v2 = true
```

**Comment by substanceof** [comment]
Если так и будет валиться - присылай лог `/tmp/vkcli-log/vklog-latest`

**Comment by CPAllianceP** [comment]
опачки, сразу заработало, сенкс
там не access_token а просто token надо было писать, всё из-за этого оказывается
