### ISSUE TITLE
Баг с музыкой: автоперескок на следующую песню

### ISSUE THREAD

**Issue by TryKote** [HaCk3Dq/vk#71]
При попытке воспроизвести аудио, крайне часто(почти всегда) происходят перелистывания на следующие песни. [Запись прилагается](https://asciinema.org/a/9vcwqd2u23ppyqt4pr5p739hu) 
Вероятно, вызвано крайне низким таймаутом ожидания подгрузки песни.(код не смотрел)

В связи с вышеперечисленным, музыку слушать просто невозможно. По пол секунды каждой песни и перескок.

_PS: за музыкальный вкус извиняйте :)_

**Comment by substanceof** [comment]
Эта проблема проявляется с новым mpv (0.23)
Пофикшено в мастере, так что решается либо сборкой с гита (на арче можно накатить `vk-cli-git`), либо откатом mpv до 0.22
