### ISSUE TITLE
Редактирование многострочных сообщений

### ISSUE THREAD

**Issue by Hummer12007** [HaCk3Dq/vk#75]
Было бы неплохо прикрутить редактирование многострочных сообщений прямо в клиент (вызов редактора) (но к этому ж еще надо добавить редактирование комманды не в исходниках, а пока таких настроек нету вроде).
А если мы в tmux, то прям в нашем окне (иначе просто вызывать терминал с редактором).
Я вот юзаю подобный патч: https://sr.ht/0EGb.patch
(ну и vk запущен в tmux с escape-time в 0 и status в off).

**Comment by HaCk3Dq** [comment]
В 0.8 постараюсь пильнуть, пока что хз как потому что при выходе из курсовой сессии все валится к херам
