### ISSUE TITLE
Не удаётся подключиться

### ISSUE THREAD

**Issue by DeaDDooMER** [HaCk3Dq/vk#9]
Собрал, запустил, токен из урла скопировал. Однако списки друзей и сообщений пусты.

> log
> rid: -52309183
> rid: -190527319
> rid: 775996185
> offline status sent (shed)
> sheduled onlineNotifier shutdown
> request: https://api.vk.com/method/execute.accountInit?v=5.50&access_token=***
> request: https://api.vk.com/method/account.setOffline?voip=0&v=5.50&access_token=***
> longpoll is waiting for api init...
> [attempt 1] network error: Timeout was reached on handle 7F3930000AB0
> [attempt 1] network error: Timeout was reached on handle 7F3940023E30
> [attempt 2] network error: Timeout was reached on handle 7F3930000AB0
> [attempt 2] network error: Timeout was reached on handle 7F3940023E30
> [attempt 3] network error: Timeout was reached on handle 7F3940023E30
> [attempt 3] network error: Timeout was reached on handle 7F3930000AB0
> [attempt 4] network error: Timeout was reached on handle 7F3940023E30
> [attempt 4] network error: Timeout was reached on handle 7F3930000AB0
> [attempt 5] network error: Timeout was reached on handle 7F3940023E30
> [attempt 5] network error: Timeout was reached on handle 7F3930000AB0
> [attempt 6] network error: Timeout was reached on handle 7F3940023E30
> [attempt 6] network error: Timeout was reached on handle 7F3930000AB0
> [attempt 7] network error: Timeout was reached on handle 7F3940023E30
> [attempt 7] network error: Timeout was reached on handle 7F3930000AB0
> [attempt 8] network error: Timeout was reached on handle 7F3940023E30
> [attempt 8] network error: Timeout was reached on handle 7F3930000AB0
> [attempt 9] network error: Timeout was reached on handle 7F3940023E30
> [attempt 9] network error: Timeout was reached on handle 7F3930000AB0
> [attempt 10] network error: Timeout was reached on handle 7F3940023E30
> Connection lost: httpget
> [attempt 10] network error: Timeout was reached on handle 7F3930000AB0
> Connection lost: httpget
> [attempt 1] network error: Timeout was reached on handle 7F3940023E30
> [attempt 1] network error: Timeout was reached on handle 7F39300009E0
> [attempt 2] network error: Timeout was reached on handle 7F39300009E0
> [attempt 2] network error: Timeout was reached on handle 7F3940023E30
> [attempt 3] network error: Timeout was reached on handle 7F39300009E0
> [attempt 3] network error: Timeout was reached on handle 7F3940023E30
> [attempt 4] network error: Timeout was reached on handle 7F39300009E0
> [attempt 4] network error: Timeout was reached on handle 7F3940023E30
> [attempt 5] network error: Timeout was reached on handle 7F39300009E0
> [attempt 5] network error: Timeout was reached on handle 7F3940023E30
> [attempt 6] network error: Timeout was reached on handle 7F39300009E0
> [attempt 6] network error: Timeout was reached on handle 7F3940023E30
> [attempt 7] network error: Timeout was reached on handle 7F39300009E0
> [attempt 7] network error: Timeout was reached on handle 7F3940023E30
> [attempt 8] network error: Timeout was reached on handle 7F39300009E0
> [attempt 8] network error: Timeout was reached on handle 7F3940023E30
> [attempt 9] network error: Timeout was reached on handle 7F39300009E0
> [attempt 9] network error: Timeout was reached on handle 7F3940023E30
> [attempt 10] network error: Timeout was reached on handle 7F39300009E0
> Connection lost: httpget
> [attempt 10] network error: Timeout was reached on handle 7F3940023E30
> Connection lost: httpget

**Comment by substanceof** [comment]
Ошибки посылает curl
Ищи проблему в своей системе
